"""Interpreter resolution for tests that shell out.

Why this exists
---------------
These tests exercise POSIX shell scripts by launching `bash` as a subprocess.
Passing the bare name ``"bash"`` as argv[0] is correct on Linux and macOS, but
silently wrong on Windows: ``CreateProcess`` searches the Windows system
directory *before* ``%PATH%``, and ``C:\\WINDOWS\\system32\\bash.exe`` is the WSL
launcher stub. Git Bash lives at ``C:\\Program Files\\Git\\bin\\bash.exe`` and is
normally not on ``%PATH%`` at all (Git ships ``...\\Git\\cmd`` there instead).

So on Windows every ``subprocess.run(["bash", ...])`` launches the WSL stub,
which — with no distro installed — prints a localized error in UTF-16LE and
exits non-zero. The tests then fail on the return code, and the undecodable
UTF-16LE bytes surface separately as a ``UnicodeDecodeError`` in subprocess's
reader thread. Neither has anything to do with the script under test.

Reordering ``%PATH%`` does *not* fix this: ``shutil.which("bash")`` starts
returning Git Bash while ``subprocess.run(["bash", ...])`` still launches the
System32 stub. The resolved path has to be baked into argv itself.

Contract
--------
On any non-Windows platform both resolvers are deliberate no-ops that return the
exact strings the tests used before, so argv is byte-identical on CI
(ubuntu-latest) and on macOS.
"""
from __future__ import annotations

import os
import shutil
from pathlib import Path

# App-execution-alias / WSL shims that resolve under these directories are not
# real interpreters; they are launcher stubs that fail or open the Store.
_WINDOWS_SHIM_DIRS = ("windows\\system32", "windowsapps", "windows\\syswow64")


def _is_windows_shim(path: str) -> bool:
    lowered = path.lower()
    return any(shim in lowered for shim in _WINDOWS_SHIM_DIRS)


def _git_bash_candidates() -> list[Path]:
    candidates: list[Path] = []

    # Preferred: derive it from the git we can actually see. Git for Windows
    # puts git.exe in <root>\cmd (or <root>\bin) and bash.exe in <root>\bin.
    git = shutil.which("git")
    if git and not _is_windows_shim(git):
        git_root = Path(git).resolve().parent.parent
        candidates.append(git_root / "bin" / "bash.exe")

    # Standard install locations, in case git itself is not on PATH.
    for base in (
        os.environ.get("ProgramFiles"),
        os.environ.get("ProgramW6432"),
        os.environ.get("ProgramFiles(x86)"),
        os.environ.get("LOCALAPPDATA"),
    ):
        if base:
            candidates.append(Path(base) / "Git" / "bin" / "bash.exe")
            candidates.append(Path(base) / "Programs" / "Git" / "bin" / "bash.exe")

    # Last resort: a PATH lookup, as long as it is not one of the stubs.
    found = shutil.which("bash")
    if found and not _is_windows_shim(found):
        candidates.append(Path(found))

    return candidates


def resolve_bash() -> str:
    """Return an argv[0] that actually starts a POSIX shell.

    Non-Windows: the literal string ``"bash"`` — unchanged behaviour.
    Windows: an absolute path to Git Bash. If none can be found we fall back to
    ``"bash"`` so the failure is the same one this environment would have had
    anyway, rather than a new one invented here.
    """
    if os.name != "nt":
        return "bash"

    for candidate in _git_bash_candidates():
        if candidate.is_file():
            return str(candidate)
    return "bash"


def resolve_python() -> str:
    """Return the interpreter name to embed in generated shell scripts.

    Must stay a *bare name*: it is substituted into shell script bodies, where a
    Windows absolute path (backslashes, spaces) would not survive quoting. The
    subprocess inherits our PATH, so a name we can resolve here is a name the
    shell can resolve too.

    CI (ubuntu-latest + actions/setup-python) always provides ``python3``, so
    this keeps returning ``"python3"`` there, exactly as before.
    """
    found = shutil.which("python3")
    if found and not _is_windows_shim(found):
        return "python3"
    return "python"


def write_lf(path: Path, text: str) -> None:
    """Write a fixture file that a POSIX shell will read, with LF endings.

    ``Path.write_text`` opens in text mode, and on Windows text mode translates
    every ``\\n`` into ``\\r\\n``. A fixture written that way is not the file CI
    produces: in CI these files are generated by earlier workflow steps running
    under Linux, so they are LF.

    The damage is silent and specific. ``while read -r full`` keeps the trailing
    ``\\r`` in the variable, so a step that looks correct builds
    ``gh api "repos/owner/name\\r"`` and GitHub's client rejects it with
    ``net/url: invalid control character in URL``. The step then takes its
    error branch and reports ``unreachable`` for a repo that is perfectly
    reachable — a false negative produced entirely by the fixture.

    Non-Windows behaviour is byte-identical to ``write_text``; ``newline="\\n"``
    only disables a translation that platform never performs.
    """
    path.write_text(text, encoding="utf-8", newline="\n")


BASH = resolve_bash()
PYTHON = resolve_python()
