#!/usr/bin/env bash
# lib.sh — shared helpers for the M005 identity-isolation scripts.
#
# SAFETY CONTRACT (read before editing):
#   - These scripts NEVER execute a privileged mutation (sudo / sysadminctl /
#     dscl -create / chown / launchctl bootout) on their own. They EMIT the
#     exact command lines for a human to review and run.
#   - Default mode is --dry-run: print the plan, mutate nothing.
#   - --emit <file> writes the raw human-run commands to <file> (0700) for the
#     human to inspect and execute. Writing that file is the only side effect.
#   - --apply is deliberately refused for privileged steps (see require_human).
#   - No secret VALUES are ever printed — only names, paths, and scopes.
#
# This file is sourced, not run. `set -euo pipefail` is the caller's choice.

II_MODE="dry-run"          # dry-run | emit
II_EMIT_FILE=""            # target file when II_MODE=emit
II_EMIT_BUF=""             # accumulated raw commands

# --- account / path constants (single source of truth) ---------------------
II_AGENT_USER="hypeproof-agent"                 # dedicated macOS OS account
II_AGENT_HOME="/Users/hypeproof-agent"          # agent home (NOT /Users/jaylee)
II_AGENT_RUNTIME="/Users/hypeproof-agent/runtime"   # repo checkouts live here
II_GH_LOGIN="hypeproof-automation"              # GitHub machine user (Phase 2)
II_HUMAN_USER="jaylee"                          # human owner — must be untouched
II_HUMAN_HOME="/Users/jaylee"

# repos the agent runtime checks out (owner/name -> transport)
II_AGENT_REPOS=(
  "jayleekr/hypeprooflab"       # write target (cron issue-solver/-filer/content)
  "jayleekr/hypeproof-harness"  # read (governance audit)
  "jayleekr/hypeproof-studio"   # read
  "jayleekr/sediment"           # read
)

# --- output helpers --------------------------------------------------------
c_head() { printf '\n=== %s ===\n' "$*"; }
c_info() { printf '  %s\n' "$*"; }
c_warn() { printf '  [!] %s\n' "$*"; }
c_ok()   { printf '  [ok] %s\n' "$*"; }
c_bad()  { printf '  [XX] %s\n' "$*"; }

# plan CMD — record a human-run command. In dry-run we PRINT it (prefixed so it
# is obviously not executed). In emit we append it to the buffer. Never runs it.
plan() {
  local cmd="$*"
  if [[ "$II_MODE" == "emit" ]]; then
    II_EMIT_BUF+="$cmd"$'\n'
  else
    printf '  $ %s\n' "$cmd"
  fi
}
plan_comment() {
  if [[ "$II_MODE" == "emit" ]]; then
    II_EMIT_BUF+="# $*"$'\n'
  else
    printf '  # %s\n' "$*"
  fi
}

# require_human — hard stop if a caller ever tries --apply on a privileged step.
require_human() {
  c_bad "REFUSED: this step changes system state (account/ownership/launchd) and"
  c_bad "         is HUMAN-ONLY. Re-run with --dry-run to review, or --emit <file>"
  c_bad "         to write the commands for you to run manually with sudo."
  exit 3
}

ii_parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --dry-run) II_MODE="dry-run" ;;
      --emit)    II_MODE="emit"; shift; II_EMIT_FILE="${1:-}";
                 [[ -z "$II_EMIT_FILE" ]] && { c_bad "--emit needs a file path"; exit 2; } ;;
      --apply)   require_human ;;
      -h|--help) II_HELP=1 ;;
      *) c_warn "ignoring unknown arg: $1" ;;
    esac
    shift
  done
}

ii_emit_flush() {
  [[ "$II_MODE" != "emit" ]] && return 0
  {
    printf '#!/usr/bin/env bash\n'
    printf '# GENERATED by %s — REVIEW EVERY LINE before running.\n' "${0##*/}"
    printf '# Privileged lines require sudo and are intentionally NOT auto-run.\n'
    printf 'set -euo pipefail\n\n'
    printf '%s' "$II_EMIT_BUF"
  } > "$II_EMIT_FILE"
  chmod 0700 "$II_EMIT_FILE"
  c_ok "wrote human-run commands to: $II_EMIT_FILE (mode 0700)"
  c_warn "inspect it, then run it yourself. This tool did NOT execute it."
}
